/* =========================================================
   Mock data — Porto Vale Pré-Venda PIX
   ========================================================= */

const SUPERINTENDENCIAS = [
  { id: 'lotus',  name: 'Lótus'  },
  { id: 'eagles', name: 'Eagles' },
];

const DIRETORIAS = [
  { id: 'fenix',     name: 'Fênix',         superid: 'lotus'  },
  { id: 'diamantes', name: 'Diamantes',     superid: 'lotus'  },
  { id: 'atena',     name: 'Atena',         superid: 'lotus'  },
  { id: 'anjos',     name: 'Anjos',         superid: 'lotus'  },
  { id: 'groove',    name: 'Groove',        superid: 'lotus'  },
  { id: 'aya',       name: 'Aya',           superid: 'eagles' },
  { id: 'quimera',   name: 'Quimera',       superid: 'eagles' },
  { id: 'bell',      name: 'Bell Breakers', superid: 'eagles' },
  { id: 'dunamis',   name: 'Dunamis',       superid: 'eagles' },
];

// 45 gerentes — 5 por diretoria
const MANAGERS = [
  // Lótus › Fênix
  { id: 'g1',  name: 'Carlos Mendes',      superid: 'lotus',  dirid: 'fenix'     },
  { id: 'g5',  name: 'Fernanda Lima',      superid: 'lotus',  dirid: 'fenix'     },
  { id: 'g6',  name: 'Ricardo Souza',      superid: 'lotus',  dirid: 'fenix'     },
  { id: 'g7',  name: 'Marcos Figueiredo',  superid: 'lotus',  dirid: 'fenix'     },
  { id: 'g8',  name: 'Daniela Rocha',      superid: 'lotus',  dirid: 'fenix'     },
  // Lótus › Diamantes
  { id: 'g2',  name: 'Juliana Faria',      superid: 'lotus',  dirid: 'diamantes' },
  { id: 'g9',  name: 'Rafael Alves',       superid: 'lotus',  dirid: 'diamantes' },
  { id: 'g10', name: 'Carolina Pires',     superid: 'lotus',  dirid: 'diamantes' },
  { id: 'g11', name: 'Thiago Santos',      superid: 'lotus',  dirid: 'diamantes' },
  { id: 'g12', name: 'Amanda Melo',        superid: 'lotus',  dirid: 'diamantes' },
  // Lótus › Atena
  { id: 'g3',  name: 'Eduardo Pinho',      superid: 'lotus',  dirid: 'atena'     },
  { id: 'g13', name: 'Lucas Vieira',       superid: 'lotus',  dirid: 'atena'     },
  { id: 'g14', name: 'Beatriz Campos',     superid: 'lotus',  dirid: 'atena'     },
  { id: 'g15', name: 'Henrique Nunes',     superid: 'lotus',  dirid: 'atena'     },
  { id: 'g16', name: 'Sofia Martins',      superid: 'lotus',  dirid: 'atena'     },
  // Lótus › Anjos
  { id: 'g4',  name: 'Renata Sales',       superid: 'lotus',  dirid: 'anjos'     },
  { id: 'g17', name: 'Felipe Ramos',       superid: 'lotus',  dirid: 'anjos'     },
  { id: 'g18', name: 'Larissa Ferreira',   superid: 'lotus',  dirid: 'anjos'     },
  { id: 'g19', name: 'Bruno Teixeira',     superid: 'lotus',  dirid: 'anjos'     },
  { id: 'g20', name: 'Vanessa Oliveira',   superid: 'lotus',  dirid: 'anjos'     },
  // Lótus › Groove
  { id: 'g21', name: 'Otávio Cunha',       superid: 'lotus',  dirid: 'groove'    },
  { id: 'g22', name: 'Isabela Moreira',    superid: 'lotus',  dirid: 'groove'    },
  { id: 'g23', name: 'Caio Barros',        superid: 'lotus',  dirid: 'groove'    },
  { id: 'g24', name: 'Priscila Gomes',     superid: 'lotus',  dirid: 'groove'    },
  { id: 'g25', name: 'Rodrigo Carvalho',   superid: 'lotus',  dirid: 'groove'    },
  // Eagles › Aya
  { id: 'g26', name: 'Aline Nascimento',   superid: 'eagles', dirid: 'aya'       },
  { id: 'g27', name: 'Diego Monteiro',     superid: 'eagles', dirid: 'aya'       },
  { id: 'g28', name: 'Tatiane Araújo',     superid: 'eagles', dirid: 'aya'       },
  { id: 'g29', name: 'Victor Correia',     superid: 'eagles', dirid: 'aya'       },
  { id: 'g30', name: 'Mônica Freitas',     superid: 'eagles', dirid: 'aya'       },
  // Eagles › Quimera
  { id: 'g31', name: 'André Silveira',     superid: 'eagles', dirid: 'quimera'   },
  { id: 'g32', name: 'Débora Pereira',     superid: 'eagles', dirid: 'quimera'   },
  { id: 'g33', name: 'Gustavo Moura',      superid: 'eagles', dirid: 'quimera'   },
  { id: 'g34', name: 'Ingrid Borges',      superid: 'eagles', dirid: 'quimera'   },
  { id: 'g35', name: 'Leonardo Lima',      superid: 'eagles', dirid: 'quimera'   },
  // Eagles › Bell Breakers
  { id: 'g36', name: 'Kamila Ribeiro',     superid: 'eagles', dirid: 'bell'      },
  { id: 'g37', name: 'Fábio Azevedo',      superid: 'eagles', dirid: 'bell'      },
  { id: 'g38', name: 'Natália Cavalcanti', superid: 'eagles', dirid: 'bell'      },
  { id: 'g39', name: 'Sérgio Paiva',       superid: 'eagles', dirid: 'bell'      },
  { id: 'g40', name: 'Juliane Matos',      superid: 'eagles', dirid: 'bell'      },
  // Eagles › Dunamis
  { id: 'g41', name: 'Paulo Caixeta',      superid: 'eagles', dirid: 'dunamis'   },
  { id: 'g42', name: 'Adriana Lopes',      superid: 'eagles', dirid: 'dunamis'   },
  { id: 'g43', name: 'Roberto Vieira',     superid: 'eagles', dirid: 'dunamis'   },
  { id: 'g44', name: 'Simone Queiroz',     superid: 'eagles', dirid: 'dunamis'   },
  { id: 'g45', name: 'Tiago Rodrigues',    superid: 'eagles', dirid: 'dunamis'   },
];

// Login personas — 1 gerente representativo por diretoria + operacional
const PERSONAS = [
  // ── Lótus ──
  { id: 'g1',  role: 'Gerente de Vendas', name: 'Carlos Mendes',    initials: 'CM', superid: 'lotus',  dirid: 'fenix',     description: 'Diretoria Fênix · Lótus'          },
  { id: 'g2',  role: 'Gerente de Vendas', name: 'Juliana Faria',    initials: 'JF', superid: 'lotus',  dirid: 'diamantes', description: 'Diretoria Diamantes · Lótus'      },
  { id: 'g3',  role: 'Gerente de Vendas', name: 'Eduardo Pinho',    initials: 'EP', superid: 'lotus',  dirid: 'atena',     description: 'Diretoria Atena · Lótus'          },
  { id: 'g4',  role: 'Gerente de Vendas', name: 'Renata Sales',     initials: 'RS', superid: 'lotus',  dirid: 'anjos',     description: 'Diretoria Anjos · Lótus'          },
  { id: 'g21', role: 'Gerente de Vendas', name: 'Otávio Cunha',     initials: 'OC', superid: 'lotus',  dirid: 'groove',    description: 'Diretoria Groove · Lótus'         },
  // ── Eagles ──
  { id: 'g26', role: 'Gerente de Vendas', name: 'Aline Nascimento', initials: 'AN', superid: 'eagles', dirid: 'aya',       description: 'Diretoria Aya · Eagles'           },
  { id: 'g31', role: 'Gerente de Vendas', name: 'André Silveira',   initials: 'AS', superid: 'eagles', dirid: 'quimera',   description: 'Diretoria Quimera · Eagles'       },
  { id: 'g36', role: 'Gerente de Vendas', name: 'Kamila Ribeiro',   initials: 'KR', superid: 'eagles', dirid: 'bell',      description: 'Diretoria Bell Breakers · Eagles' },
  { id: 'g41', role: 'Gerente de Vendas', name: 'Paulo Caixeta',    initials: 'PC', superid: 'eagles', dirid: 'dunamis',   description: 'Diretoria Dunamis · Eagles'       },
  // ── Operacional ──
  { id: 'financeiro',     role: 'Financeiro',        name: 'Marcelo Tavares', initials: 'MT', description: 'Importa extrato bancário e vincula valores'       },
  { id: 'backoffice_adm', role: 'Aprovação de Cota', name: 'Patrícia Lopes',  initials: 'PL', description: 'Confere cotas prontas e lança na administradora' },
];

const CAMPAIGNS = [
  {
    id: 'CMP-2026-08',
    name: 'Acelera Agosto 2026',
    start: '2026-07-28',
    launch: '2026-08-15',
    status: 'Ativa',
  },
];

/*
  Status flow:
    aguardando_financeiro  → gerente subiu comprovante, financeiro ainda não vinculou extrato
    aguardando_contrato    → extrato vinculado, gerente precisa enviar contrato
    pronto                 → comprovante + extrato + contrato OK, esperando Aprovação de Cota
    concluida              → cota lançada e venda encerrada
*/

let RECORDS = [
  // ── Carlos (g1 · Fênix / Lótus) ──
  {
    id: 'PV-001',
    campanhaId: 'CMP-2026-08',
    gerenteId: 'g1',
    gerenteNome: 'Carlos Mendes',
    nomeVendedor: 'Carlos Mendes',
    nomePagador: 'João da Silva',
    nomeCliente: 'João da Silva',
    mesmoNomeContrato: true,
    motivoDiferenca: '',
    valorComprovante: 1240.00,
    dataHora: '2026-06-08 14:32',
    comprovante: { fileName: 'pix_joao_silva.pdf', uploadedAt: '2026-06-08 14:45' },
    observacao: '',
    status: 'aguardando_financeiro',
    extrato: null,
    valorReal: null,
    contrato: null,
    history: [
      { when: '2026-06-08 14:45', who: 'Carlos (Gerente)', what: 'Pré-venda criada · comprovante enviado' },
    ],
  },
  {
    id: 'PV-002',
    campanhaId: 'CMP-2026-08',
    gerenteId: 'g1',
    gerenteNome: 'Carlos Mendes',
    nomeVendedor: 'Carlos Mendes',
    nomePagador: 'Maria Oliveira',
    nomeCliente: 'Maria Oliveira',
    mesmoNomeContrato: true,
    motivoDiferenca: '',
    valorComprovante: 980.00,
    dataHora: '2026-06-03 15:18',
    comprovante: { fileName: 'pix_maria_oliveira.jpg', uploadedAt: '2026-06-03 15:25' },
    observacao: '',
    status: 'aguardando_contrato',
    extrato: { remetente: 'MARIA OLIVEIRA', valor: 980.00, dataHora: '2026-06-03 15:18', tipo: 'auto' },
    valorReal: null,
    contrato: null,
    history: [
      { when: '2026-06-03 15:25', who: 'Carlos (Gerente)', what: 'Pré-venda criada · comprovante enviado' },
      { when: '2026-06-04 09:00', who: 'Sistema',          what: 'PIX vinculado automaticamente ao extrato bancário · R$ 980,00' },
      { when: '2026-06-04 09:00', who: 'Sistema',          what: 'Aguardando envio do contrato pelo gerente' },
    ],
  },
  {
    id: 'PV-003',
    campanhaId: 'CMP-2026-08',
    gerenteId: 'g1',
    gerenteNome: 'Carlos Mendes',
    nomeVendedor: 'Carlos Mendes',
    nomePagador: 'Bruno Costa',
    nomeCliente: 'Bruno Costa',
    mesmoNomeContrato: true,
    motivoDiferenca: '',
    valorComprovante: 1180.00,
    dataHora: '2026-06-04 09:48',
    comprovante: { fileName: 'pix_bruno_costa.pdf', uploadedAt: '2026-06-04 10:02' },
    observacao: '',
    status: 'diferenca_pendente',
    extrato: { remetente: 'BRUNO COSTA', valor: 1180.00, dataHora: '2026-06-04 09:48', tipo: 'auto' },
    valorReal: 1260.00,
    contrato: { fileName: 'contrato_bruno.pdf', uploadedAt: '2026-06-05 16:30', cota: '0894' },
    comprovanteComplementar: null,
    chamadoReembolso: null,
    history: [
      { when: '2026-06-04 10:02', who: 'Carlos (Gerente)', what: 'Pré-venda criada · comprovante enviado' },
      { when: '2026-06-04 14:00', who: 'Sistema',          what: 'PIX vinculado ao extrato · R$ 1.180,00' },
      { when: '2026-06-05 16:30', who: 'Carlos (Gerente)', what: 'Contrato enviado · valor real R$ 1.260 · Cota 0894' },
      { when: '2026-06-05 16:30', who: 'Sistema',          what: 'Diferença detectada · cliente pagou R$ 1.180 mas contrato exige R$ 1.260 · aguardando comprovante complementar de R$ 80,00' },
    ],
  },
  {
    id: 'PV-011',
    campanhaId: 'CMP-2026-08',
    gerenteId: 'g1',
    gerenteNome: 'Carlos Mendes',
    nomeVendedor: 'Carlos Mendes',
    nomePagador: 'Ana Beatriz Souza',
    nomeCliente: 'Ana Beatriz Souza',
    mesmoNomeContrato: true,
    motivoDiferenca: '',
    valorComprovante: 1350.00,
    dataHora: '2026-06-07 11:05',
    comprovante: { fileName: 'pix_ana_beatriz.pdf', uploadedAt: '2026-06-07 11:15' },
    observacao: '',
    status: 'pronto',
    extrato: { remetente: 'ANA BEATRIZ SOUZA', valor: 1350.00, dataHora: '2026-06-07 11:05', tipo: 'auto' },
    valorReal: 1350.00,
    contrato: { fileName: 'contrato_ana_beatriz.pdf', uploadedAt: '2026-06-08 10:40', cota: '0901' },
    history: [
      { when: '2026-06-07 11:15', who: 'Carlos (Gerente)', what: 'Pré-venda criada · comprovante enviado' },
      { when: '2026-06-07 16:00', who: 'Sistema',          what: 'PIX vinculado automaticamente ao extrato · R$ 1.350,00' },
      { when: '2026-06-08 10:40', who: 'Carlos (Gerente)', what: 'Contrato enviado · valor real R$ 1.350,00 · Cota 0901' },
      { when: '2026-06-08 10:40', who: 'Sistema',          what: 'Comprovante, extrato e contrato confirmados · pronto para aprovação de cota' },
    ],
  },
  {
    id: 'PV-012',
    campanhaId: 'CMP-2026-08',
    gerenteId: 'g1',
    gerenteNome: 'Carlos Mendes',
    nomeVendedor: 'Carlos Mendes',
    nomePagador: 'Ricardo Alves',
    nomeCliente: 'Ricardo Alves',
    mesmoNomeContrato: true,
    motivoDiferenca: '',
    valorComprovante: 1120.00,
    dataHora: '2026-06-02 09:30',
    comprovante: { fileName: 'pix_ricardo_alves.pdf', uploadedAt: '2026-06-02 09:42' },
    observacao: '',
    status: 'concluida',
    extrato: { remetente: 'RICARDO ALVES', valor: 1120.00, dataHora: '2026-06-02 09:30', tipo: 'auto' },
    valorReal: 1120.00,
    contrato: { fileName: 'contrato_ricardo_alves.pdf', uploadedAt: '2026-06-03 14:20', cota: '0887' },
    history: [
      { when: '2026-06-02 09:42', who: 'Carlos (Gerente)',     what: 'Pré-venda criada · comprovante enviado' },
      { when: '2026-06-02 15:00', who: 'Sistema',              what: 'PIX vinculado automaticamente ao extrato · R$ 1.120,00' },
      { when: '2026-06-03 14:20', who: 'Carlos (Gerente)',     what: 'Contrato enviado · Cota 0887' },
      { when: '2026-06-04 09:00', who: 'Patrícia (Aprovação)', what: 'Cota 0887 lançada na administradora · venda concluída' },
    ],
  },

  // ── Juliana (g2 · Diamantes / Lótus) ──
  {
    id: 'PV-004',
    campanhaId: 'CMP-2026-08',
    gerenteId: 'g2',
    gerenteNome: 'Juliana Faria',
    nomeVendedor: 'Ana Paula Reis',
    nomePagador: 'Roberta Almeida',
    nomeCliente: 'Roberta Almeida',
    mesmoNomeContrato: true,
    motivoDiferenca: '',
    valorComprovante: 1400.00,
    dataHora: '2026-06-04 11:22',
    comprovante: { fileName: 'pix_roberta.pdf', uploadedAt: '2026-06-04 11:30' },
    observacao: 'Cliente ligou confirmando pagamento',
    status: 'aguardando_financeiro',
    extrato: null,
    valorReal: null,
    contrato: null,
    history: [
      { when: '2026-06-04 11:30', who: 'Juliana (Gerente)', what: 'Pré-venda criada · comprovante enviado' },
    ],
  },
  {
    id: 'PV-005',
    campanhaId: 'CMP-2026-08',
    gerenteId: 'g2',
    gerenteNome: 'Juliana Faria',
    nomeVendedor: 'Rafael Costa',
    nomePagador: 'Diego Martins',
    nomeCliente: 'Diego Martins',
    mesmoNomeContrato: true,
    motivoDiferenca: '',
    valorComprovante: 1080.00,
    dataHora: '2026-06-06 09:21',
    comprovante: { fileName: 'pix_diego.pdf', uploadedAt: '2026-06-06 09:30' },
    observacao: '',
    status: 'aguardando_contrato',
    extrato: { remetente: 'DIEGO MARTINS', valor: 1080.00, dataHora: '2026-06-06 09:21', tipo: 'auto' },
    valorReal: null,
    contrato: null,
    history: [
      { when: '2026-06-06 09:30', who: 'Juliana (Gerente)', what: 'Pré-venda criada · comprovante enviado' },
      { when: '2026-06-06 16:00', who: 'Sistema',           what: 'PIX vinculado ao extrato · R$ 1.080,00' },
    ],
  },
  {
    id: 'PV-006',
    campanhaId: 'CMP-2026-08',
    gerenteId: 'g2',
    gerenteNome: 'Juliana Faria',
    nomeVendedor: 'Ana Paula Reis',
    nomePagador: 'Vinícius Reis',
    nomeCliente: 'Vinícius Reis',
    mesmoNomeContrato: true,
    motivoDiferenca: '',
    valorComprovante: 1260.00,
    dataHora: '2026-06-08 08:15',
    comprovante: { fileName: 'pix_vinicius.pdf', uploadedAt: '2026-06-08 08:25' },
    observacao: '',
    status: 'pronto',
    extrato: { remetente: 'VINICIUS REIS', valor: 1260.00, dataHora: '2026-06-08 08:15', tipo: 'auto' },
    valorReal: 1260.00,
    contrato: { fileName: 'contrato_vinicius.pdf', uploadedAt: '2026-06-09 09:10', cota: '0898' },
    history: [
      { when: '2026-06-08 08:25', who: 'Juliana (Gerente)', what: 'Pré-venda criada · comprovante enviado' },
      { when: '2026-06-08 14:00', who: 'Sistema',           what: 'PIX vinculado ao extrato · R$ 1.260,00' },
      { when: '2026-06-09 09:10', who: 'Juliana (Gerente)', what: 'Contrato enviado · Cota 0898' },
    ],
  },

  // ── Eduardo (g3 · Atena / Lótus) ──
  {
    id: 'PV-007',
    campanhaId: 'CMP-2026-08',
    gerenteId: 'g3',
    gerenteNome: 'Eduardo Pinho',
    nomeVendedor: 'Lucas Ferreira',
    nomePagador: 'Larissa Vieira',
    nomeCliente: 'Larissa Vieira',
    mesmoNomeContrato: true,
    motivoDiferenca: '',
    valorComprovante: 1320.00,
    dataHora: '2026-06-05 16:12',
    comprovante: { fileName: 'pix_larissa.pdf', uploadedAt: '2026-06-05 16:20' },
    observacao: '',
    status: 'pronto',
    extrato: { remetente: 'LARISSA VIEIRA', valor: 1320.00, dataHora: '2026-06-05 16:12', tipo: 'auto' },
    valorReal: 1320.00,
    contrato: { fileName: 'contrato_larissa.pdf', uploadedAt: '2026-06-06 11:00', cota: '0897' },
    history: [
      { when: '2026-06-05 16:20', who: 'Eduardo (Gerente)', what: 'Pré-venda criada · comprovante enviado' },
      { when: '2026-06-06 08:00', who: 'Sistema',           what: 'PIX vinculado ao extrato · R$ 1.320,00' },
      { when: '2026-06-06 11:00', who: 'Eduardo (Gerente)', what: 'Contrato enviado · Cota 0897' },
    ],
  },
  {
    id: 'PV-008',
    campanhaId: 'CMP-2026-08',
    gerenteId: 'g3',
    gerenteNome: 'Eduardo Pinho',
    nomeVendedor: 'Lucas Ferreira',
    nomePagador: 'Camila Andrade',
    nomeCliente: 'Camila Andrade',
    mesmoNomeContrato: true,
    motivoDiferenca: '',
    valorComprovante: 1450.00,
    dataHora: '2026-06-07 10:00',
    comprovante: { fileName: 'pix_camila.pdf', uploadedAt: '2026-06-07 10:12' },
    observacao: 'Pagamento feito por transferência antes do PIX ser configurado',
    status: 'aguardando_financeiro',
    extrato: null,
    valorReal: null,
    contrato: null,
    history: [
      { when: '2026-06-07 10:12', who: 'Eduardo (Gerente)', what: 'Pré-venda criada · comprovante enviado' },
    ],
  },

  // ── Renata (g4 · Anjos / Lótus) ──
  {
    id: 'PV-009',
    campanhaId: 'CMP-2026-08',
    gerenteId: 'g4',
    gerenteNome: 'Renata Sales',
    nomeVendedor: 'Fernanda Dias',
    nomePagador: 'Helena Souza',
    nomeCliente: 'Pedro Souza',
    mesmoNomeContrato: false,
    motivoDiferenca: 'Mãe comprando para o filho',
    valorComprovante: 1000.00,
    dataHora: '2026-06-05 10:11',
    comprovante: { fileName: 'pix_helena_souza.pdf', uploadedAt: '2026-06-05 10:20' },
    observacao: 'Mãe (Helena Souza) pagando em nome do filho (Pedro Souza)',
    status: 'diferenca_pendente',
    extrato: { remetente: 'HELENA SOUZA', valor: 1000.00, dataHora: '2026-06-05 10:11', tipo: 'manual' },
    valorReal: 950.00,
    contrato: { fileName: 'contrato_pedro_souza.pdf', uploadedAt: '2026-06-06 09:55', cota: '0896' },
    comprovanteComplementar: null,
    chamadoReembolso: null,
    history: [
      { when: '2026-06-05 10:20', who: 'Renata (Gerente)',     what: 'Pré-venda criada · pagador ≠ titular (mãe → filho)' },
      { when: '2026-06-05 15:00', who: 'Marcelo (Financeiro)', what: 'PIX vinculado manualmente · remetente: Helena Souza' },
      { when: '2026-06-06 09:55', who: 'Renata (Gerente)',     what: 'Contrato enviado · Cota 0896' },
      { when: '2026-06-06 09:55', who: 'Sistema',              what: 'Pagamento excede o valor do contrato · R$ 50,00 a devolver ao cliente · aguardando abertura de chamado' },
    ],
  },
  {
    id: 'PV-010',
    campanhaId: 'CMP-2026-08',
    gerenteId: 'g4',
    gerenteNome: 'Renata Sales',
    nomeVendedor: 'Tiago Moraes',
    nomePagador: 'Tatiana Lima',
    nomeCliente: 'Tatiana Lima',
    mesmoNomeContrato: true,
    motivoDiferenca: '',
    valorComprovante: 1100.00,
    dataHora: '2026-06-06 13:00',
    comprovante: { fileName: 'pix_tatiana_lima.jpg', uploadedAt: '2026-06-06 13:18' },
    observacao: 'Cliente confirmou pagamento por telefone às 13h',
    status: 'aguardando_contrato',
    extrato: { remetente: 'TATIANA LIMA', valor: 1100.00, dataHora: '2026-06-06 13:00', tipo: 'manual' },
    valorReal: null,
    contrato: null,
    history: [
      { when: '2026-06-06 13:18', who: 'Renata (Gerente)',     what: 'Pré-venda criada · comprovante enviado' },
      { when: '2026-06-07 11:00', who: 'Marcelo (Financeiro)', what: 'PIX vinculado manualmente · R$ 1.100,00' },
    ],
  },

  // ── Otávio (g21 · Groove / Lótus) ──
  {
    id: 'PV-013',
    campanhaId: 'CMP-2026-08',
    gerenteId: 'g21',
    gerenteNome: 'Otávio Cunha',
    nomeVendedor: 'Otávio Cunha',
    nomePagador: 'Rodrigo Silva',
    nomeCliente: 'Rodrigo Silva',
    mesmoNomeContrato: true,
    motivoDiferenca: '',
    valorComprovante: 1190.00,
    dataHora: '2026-06-09 10:15',
    comprovante: { fileName: 'pix_rodrigo_silva.pdf', uploadedAt: '2026-06-09 10:22' },
    observacao: '',
    status: 'aguardando_financeiro',
    extrato: null,
    valorReal: null,
    contrato: null,
    history: [
      { when: '2026-06-09 10:22', who: 'Otávio (Gerente)', what: 'Pré-venda criada · comprovante enviado' },
    ],
  },

  // ── Aline (g26 · Aya / Eagles) ──
  {
    id: 'PV-014',
    campanhaId: 'CMP-2026-08',
    gerenteId: 'g26',
    gerenteNome: 'Aline Nascimento',
    nomeVendedor: 'Aline Nascimento',
    nomePagador: 'Carla Fontana',
    nomeCliente: 'Carla Fontana',
    mesmoNomeContrato: true,
    motivoDiferenca: '',
    valorComprovante: 1380.00,
    dataHora: '2026-06-07 14:40',
    comprovante: { fileName: 'pix_carla_fontana.pdf', uploadedAt: '2026-06-07 14:50' },
    observacao: '',
    status: 'aguardando_contrato',
    extrato: { remetente: 'CARLA FONTANA', valor: 1380.00, dataHora: '2026-06-07 14:40', tipo: 'auto' },
    valorReal: null,
    contrato: null,
    history: [
      { when: '2026-06-07 14:50', who: 'Aline (Gerente)', what: 'Pré-venda criada · comprovante enviado' },
      { when: '2026-06-08 09:00', who: 'Sistema',         what: 'PIX vinculado automaticamente ao extrato · R$ 1.380,00' },
    ],
  },

  // ── André (g31 · Quimera / Eagles) ──
  {
    id: 'PV-015',
    campanhaId: 'CMP-2026-08',
    gerenteId: 'g31',
    gerenteNome: 'André Silveira',
    nomeVendedor: 'André Silveira',
    nomePagador: 'Felipe Drummond',
    nomeCliente: 'Felipe Drummond',
    mesmoNomeContrato: true,
    motivoDiferenca: '',
    valorComprovante: 1560.00,
    dataHora: '2026-06-05 11:00',
    comprovante: { fileName: 'pix_felipe_drummond.pdf', uploadedAt: '2026-06-05 11:12' },
    observacao: '',
    status: 'pronto',
    extrato: { remetente: 'FELIPE DRUMMOND', valor: 1560.00, dataHora: '2026-06-05 11:00', tipo: 'auto' },
    valorReal: 1560.00,
    contrato: { fileName: 'contrato_felipe_drummond.pdf', uploadedAt: '2026-06-06 15:30', cota: '0910' },
    history: [
      { when: '2026-06-05 11:12', who: 'André (Gerente)', what: 'Pré-venda criada · comprovante enviado' },
      { when: '2026-06-05 16:00', who: 'Sistema',         what: 'PIX vinculado automaticamente ao extrato · R$ 1.560,00' },
      { when: '2026-06-06 15:30', who: 'André (Gerente)', what: 'Contrato enviado · Cota 0910' },
      { when: '2026-06-06 15:30', who: 'Sistema',         what: 'Comprovante, extrato e contrato confirmados · pronto para aprovação de cota' },
    ],
  },

  // ── Kamila (g36 · Bell Breakers / Eagles) ──
  {
    id: 'PV-016',
    campanhaId: 'CMP-2026-08',
    gerenteId: 'g36',
    gerenteNome: 'Kamila Ribeiro',
    nomeVendedor: 'Kamila Ribeiro',
    nomePagador: 'Juliana Castro',
    nomeCliente: 'Juliana Castro',
    mesmoNomeContrato: true,
    motivoDiferenca: '',
    valorComprovante: 1050.00,
    dataHora: '2026-06-01 13:30',
    comprovante: { fileName: 'pix_juliana_castro.pdf', uploadedAt: '2026-06-01 13:42' },
    observacao: '',
    status: 'concluida',
    extrato: { remetente: 'JULIANA CASTRO', valor: 1050.00, dataHora: '2026-06-01 13:30', tipo: 'auto' },
    valorReal: 1050.00,
    contrato: { fileName: 'contrato_juliana_castro.pdf', uploadedAt: '2026-06-02 10:15', cota: '0905' },
    history: [
      { when: '2026-06-01 13:42', who: 'Kamila (Gerente)',     what: 'Pré-venda criada · comprovante enviado' },
      { when: '2026-06-01 18:00', who: 'Sistema',              what: 'PIX vinculado automaticamente ao extrato · R$ 1.050,00' },
      { when: '2026-06-02 10:15', who: 'Kamila (Gerente)',     what: 'Contrato enviado · Cota 0905' },
      { when: '2026-06-02 17:00', who: 'Patrícia (Aprovação)', what: 'Cota 0905 lançada na administradora · venda concluída' },
    ],
  },

  // ── Paulo (g41 · Dunamis / Eagles) ──
  {
    id: 'PV-017',
    campanhaId: 'CMP-2026-08',
    gerenteId: 'g41',
    gerenteNome: 'Paulo Caixeta',
    nomeVendedor: 'Paulo Caixeta',
    nomePagador: 'Marcos Vinicius',
    nomeCliente: 'Marcos Vinicius',
    mesmoNomeContrato: true,
    motivoDiferenca: '',
    valorComprovante: 1300.00,
    dataHora: '2026-06-08 16:00',
    comprovante: { fileName: 'pix_marcos_vinicius.pdf', uploadedAt: '2026-06-08 16:10' },
    observacao: '',
    status: 'diferenca_pendente',
    extrato: { remetente: 'MARCOS VINICIUS', valor: 1300.00, dataHora: '2026-06-08 16:00', tipo: 'auto' },
    valorReal: 1250.00,
    contrato: { fileName: 'contrato_marcos_vinicius.pdf', uploadedAt: '2026-06-09 09:00', cota: '0921' },
    comprovanteComplementar: null,
    chamadoReembolso: null,
    history: [
      { when: '2026-06-08 16:10', who: 'Paulo (Gerente)', what: 'Pré-venda criada · comprovante enviado' },
      { when: '2026-06-08 18:00', who: 'Sistema',         what: 'PIX vinculado automaticamente ao extrato · R$ 1.300,00' },
      { when: '2026-06-09 09:00', who: 'Paulo (Gerente)', what: 'Contrato enviado · Cota 0921' },
      { when: '2026-06-09 09:00', who: 'Sistema',         what: 'Pagamento excede o valor do contrato · R$ 50,00 a devolver ao cliente · aguardando abertura de chamado' },
    ],
  },
];

// Histórico de extratos importados
let EXTRATO_HISTORY = [
  {
    id: 'EXT-001',
    fileName: 'extrato_01_06_junho.pdf',
    importedAt: '2026-06-02 08:45',
    importedBy: 'Marcelo Tavares',
    autoLinked: 3,
    pending: 1,
    entries: [
      { remetente: 'MARIA OLIVEIRA',  valor: 980.00,  dataHora: '2026-06-03 15:18', vinculadoId: 'PV-002', vinculadoNome: 'Maria Oliveira',  status: 'auto'    },
      { remetente: 'RICARDO ALVES',   valor: 1120.00, dataHora: '2026-06-02 09:30', vinculadoId: 'PV-012', vinculadoNome: 'Ricardo Alves',   status: 'auto'    },
      { remetente: 'VINICIUS REIS',   valor: 1260.00, dataHora: '2026-06-08 08:15', vinculadoId: 'PV-006', vinculadoNome: 'Vinícius Reis',   status: 'auto'    },
      { remetente: 'FERNANDA COUTO',  valor: 1200.00, dataHora: '2026-06-06 15:44', vinculadoId: null,     vinculadoNome: null,              status: 'pending' },
    ],
  },
  {
    id: 'EXT-002',
    fileName: 'extrato_06_junho.pdf',
    importedAt: '2026-06-07 09:10',
    importedBy: 'Marcelo Tavares',
    autoLinked: 3,
    pending: 2,
    entries: [
      { remetente: 'DIEGO MARTINS',   valor: 1080.00, dataHora: '2026-06-06 09:21', vinculadoId: 'PV-005', vinculadoNome: 'Diego Martins',   status: 'auto'    },
      { remetente: 'LARISSA VIEIRA',  valor: 1320.00, dataHora: '2026-06-05 16:12', vinculadoId: 'PV-007', vinculadoNome: 'Larissa Vieira',  status: 'auto'    },
      { remetente: 'ANA BEATRIZ SOUZA',valor:1350.00, dataHora: '2026-06-07 11:05', vinculadoId: 'PV-011', vinculadoNome: 'Ana Beatriz Souza',status:'auto'    },
      { remetente: 'SERGIO PINTO',    valor: 1750.00, dataHora: '2026-06-01 08:55', vinculadoId: null,     vinculadoNome: null,              status: 'pending' },
      { remetente: 'TATIANA LIMA',    valor: 1100.00, dataHora: '2026-06-06 13:00', vinculadoId: 'PV-010', vinculadoNome: 'Tatiana Lima',    status: 'manual'  },
    ],
  },
];

// PIX no extrato sem pré-venda correspondente
let EXTRATO_ORPHANS = [
  { id: 'E-100', remetente: 'FERNANDA COUTO',    valor: 1200.00, dataHora: '2026-06-06 15:44', chavePix: '(não disponível)' },
  { id: 'E-101', remetente: 'SERGIO PINTO',      valor: 1750.00, dataHora: '2026-06-01 08:55', chavePix: '(não disponível)' },
  { id: 'E-102', remetente: 'ROBERTA C ALMEIDA', valor: 1400.00, dataHora: '2026-06-04 11:22', chavePix: '(não disponível)' },
  { id: 'E-103', remetente: 'RODRIGO SILVA',     valor: 1190.00, dataHora: '2026-06-09 10:15', chavePix: '(não disponível)' },
];

const STATUS_CHIP = {
  'aguardando_financeiro': 'chip-amber',
  'aguardando_contrato':   'chip-blue',
  'diferenca_pendente':    'chip-orange',
  'pronto':                'chip-green',
  'concluida':             'chip-teal',
};

const STATUS_LABEL = {
  'aguardando_financeiro': 'Análise financeira',
  'aguardando_contrato':   'Aguardando contrato',
  'diferenca_pendente':    'Diferença pendente',
  'pronto':                'Pronto para aprovação',
  'concluida':             'Concluída',
};
